### ISSUE TITLE
TTGO T-Display

### ISSUE THREAD

**Issue by dolence** [farpatch/farpatch#59]
Would this run on a Lillygo TTGO T-Display?

**Comment by xobs** [comment]
It should! The ESP32 version ought to work, though you'll probably need to update the pin mappings.

**Comment by dolence** [comment]
Thank you very much. Still fighting with Espressif VS Code plugin. It's giving me some error messages after installing. Did you ever saw something like this? May it be because I'm using ZSH?

```
Python requirements has been installed
/bin/sh: 1: riscv32-esp-elf-gcc: not found
Command failed: riscv32-esp-elf-gcc --version
/bin/sh: 1: riscv32-esp-elf-gcc: not found
Error checking riscv32-esp-elf version
Error: Command failed: riscv32-esp-elf-gcc --version
/bin/sh: 1: riscv32-esp-elf-gcc: not found

/bin/sh: 1: xtensa-esp-elf-gcc: not found
Command failed: xtensa-esp-elf-gcc --version
/bin/sh: 1: xtensa-esp-elf-gcc: not found
Error checking xtensa-esp-elf version
Error: Command failed: xtensa-esp-elf-gcc --version
/bin/sh: 1: xtensa-esp-elf-gcc: not found
```

**Comment by xobs** [comment]
Looks like you forgot to source `activate.sh`, or possibly the installation by `install.sh` didn't correctly finish.

**Comment by dolence** [comment]
I'm trying to build without using any IDE. I made the pin configuration in menuconfig but when I try to build this error is shown:

```
/home/dolence/farpatch/main/platform.c: In function 'platform_init':
/home/dolence/farpatch/main/platform.c:120:24: error: 'CONFIG_VREF_ADC_GPIO' undeclared (first use in this function); did you mean 'CONFIG_VREF_ADC_UNIT'?
  120 |         gpio_reset_pin(CONFIG_VREF_ADC_GPIO);
      |                        ^~~~~~~~~~~~~~~~~~~~
      |                        CONFIG_VREF_ADC_UNIT
```
Any thoughts?

**Comment by dolence** [comment]
I cancompile one of the default templates, but if I choose custom, even with the default configuration the build doesn't complete. Also, a default pin definition for TDI GPIO is missing.

**Comment by dolence** [comment]
OK, so I get with working adding the missing #define. Now, I'm trying to flash an STM32 through Zephyr West and I'm kind of lost. I see you are using Zephyr on your terminal. I've these lines add to my cmake file:

`board_runner_args(blackmagicprobe "--connect-rst")
include(${ZEPHYR_BASE}/boards/common/blackmagicprobe.board.cmake)`

Now, how do I make to tell west to use bmp over wifi?

`west flash --runner blackmagicprobe       
-- west flash: rebuilding
[1/1] cd /home/dolence/zephyrproject/apps/termo-r...roject/apps/termo-riverdi/build/zephyr/zephyr.elf
-- west flash: using runner blackmagicprobe
FATAL ERROR: cannot find any valid port matching /dev/ttyACM*
`

**Comment by xobs** [comment]
Things might be faster now due to refactoring. Please let me know if this is not the case.
