### ISSUE TITLE
Extremly slow communication between GDB and far patch

### ISSUE THREAD

**Issue by dobryj** [farpatch/farpatch#61]
Hello,
with last commits a have problem with slooooow communication between GDB and GDBstub in farpatch. In reality any request took 4~5 sec to response. And because loading SW need many of them, loading took several minutes instead expected seconds.
Last working version is commit 31506b148d94cf5479bf1fd7c031206a752c1494
First broken is 297dfe69aa6af97e2daf9c739c41d2a58b0db04a

I try ESP-IDF latest release (5.1.1) and last master commit (b3f7e2c8a4d354df8ef8558ea7caddc07283a57b) without any difference.
Used GDB is latest from STM32cubeIDE (IDE version 1.14.1, GNU gdb (GNU Tools for STM32 11.3.rel1.20230912-1600) 12.1.90.20220802-git)

I try it on two different HWs, ESP32 and ESP32C3 without any difference)

Compilled with Python 3.11 (Linux Manjaro based on Arch)

Any idea?

**Comment by dobryj** [comment]
I also try direct Wifi communication and communication over the Wifi AP. No diffrence.

**Comment by dobryj** [comment]
And GDB init script is

set target-async on
set mem inaccessible-by-default off
target extended-remote 192.168.62.153:2022
monitor version
monitor swdp_scan
attach 1
monitor rtt

**Comment by dolence** [comment]
I'm having similar issues, as described: [here](https://github.com/farpatch/farpatch/issues/59#issuecomment-1922228702)

**Comment by xobs** [comment]
I wonder if RTT isn't a cause of this issue. Since RTT performs a lot of reads. It should be throttled, but maybe that isn't working right.

**Comment by xobs** [comment]
I did notice that upstream Blackmagic now prints out all GDB packets whereas they didn't used to do that.

Does this patch help at all?

```patch
diff --git a/components/blackmagic/general.h b/components/blackmagic/general.h
index 4bd047ee..adde94f6 100644
--- a/components/blackmagic/general.h
+++ b/components/blackmagic/general.h
@@ -80,10 +80,13 @@
        do {                                         \
                ESP_LOGI_BMP("BMP:I", x, ##__VA_ARGS__); \
        } while (0)
+#if 0
 #define DEBUG_GDB(x, ...)                      \
        do {                                       \
                ESP_LOGI_BMP("GDB", x, ##__VA_ARGS__); \
        } while (0)
+#endif
+#define DEBUG_GDB(x, ...)    PRINT_NOOP()
 #define DEBUG_TARGET(x, ...)                    \
        do {                                        \
                ESP_LOGI_BMP("TARG", x, ##__VA_ARGS__); \
```

**Comment by xobs** [comment]
I haven't seen this issue lately, and I've been doing a lot of RTT. Please let me know if this issue still exists and I will reopen it.
